oldProduct = {
    'IreName': '1212custom_image',
    'PrSKU': 'URED1101',
    'RomanceCopy': "A stylish and stable computer desk is your ideal choice. Welcome to purchase this desk. Tempered glass computer desk meets all your needs, stylish and avant-garde design, sturdy and stable X-shaped carbon steel structure, very stable and light, offers you a suitable space wherever you work at. Features: 0.2'' thickened tempered glass tabletop. 2''widened X-shaped carbon steel frame. Reinforced beam design. Desktop threading holes to avoid messy cables. The rounded corners are designed to prevent children from bumping. 4 PCS non-slip mats to avoid scratching the floor. Wide usage: This desk is perfect for office, study room, bedroom, living room, workstation, hotel room, and co-working spaces as a computer desk, meeting desk, study table, writing desk, gaming desk, corner desk, and shelves, etc.  Frame: X shape carbon steel frame. Self-assembly: All tools included.",
    'PrSpecialUnitPerBox': '1.0',
    'PrDisplaySetQty': 1,
    'PrDisplaySKU': 'W010799654',
    'PpTradeOnly': 0,
    'WhiteGloveFreeShipMsgType': '0',
    'SalesFlagId': 1,
    'PrMaID': '38454',
    'PrName': 'Jolyne Glass Desk',
    'PwrReviewRating2': 1,
    'SilhouetteIreID': 0,
    'PrSpecialSkuType': '0',
    'PwrBayesianRating': 3,
    'ParentBclgID': 1,
    'PrForceQtyMultiplier': 1,
    'hasObjModel': 0,
    'hasUnityModel': 0,
    'EnvironmentalIreID': 221690558,
    'PrReviewRating': '1.0',
    'top_PojText': 'Sale',
    'IrpIreID': '221690558',
    'SiMaxHours': 0,
    'ShipsTo': 0,
    'PrAdminOnly': '0',
    'PrFixedStdShipping': 0,
    'PrNew': 0,
    'top_PojFlagColor': '1',
    'PwrReviewRating': 1,
    'OptionPayload': None,
    'IraFileExtension': 'jpg',
    'ClearanceQty': 0,
    'masterClID': '32',
    'PrShipUpgrade': '0',
    'PrMinOrderQty': 1,
    'SALES_COUNT': 0,
    'MaName': 'Breakwater Bay',
    'PwrPrNumFullReviews': 0,
    'PrManuPartNum': 'X121800765',
    'PrKit': '0',
    'PiCategory': '',
    'IreMaID': '2664',
    'PrFreeGround': '0',
    'PrSvID': '1',
    'clearance_admin_only': False,
    'ProductFeaturesArray': [
        "Tempered glass computer desk: This computer desk glass top is thickened tempered glass, with a scratch-resistant, anti-collision, and waterproof design, which protect the office desk surface from daily wear and tear and very easy to clean, so you can use it for many years. the appearance and functionality are classy and efficient in-home/office.', 'Carbon steel frame structure: The main frame of this desk table for computer uses X-shape carbon steel frame structure. The reinforced beam ensures that the table will not Shake. Desk in a very sturdy frame that is designed in an edgy architectural look to support all your office essentials, no serious shaking or movement, very stable and secure.', 'Versatility: The edge of this computer desk is designed with rounded corners, which can better prevent your children from getting injured by sharp edges. There is a hole on the surface of the table for your wires to pass through to keep your table clean.", "Computer writing desk: Suitable for study, bedroom, living room, kitchen, children's room, office. Can be a computer desk, learning tables, game tables, secretarial desk. Wide desktop (55.1'' x 23.6'' x 29.5'') provides ample space for computer, monitor, printer, and other office supplies as a computer desk, study desk, gaming desk, writing table, etc."
    ],
    'PrRestrictionsBitmap': [0],
    'classIDsList': [32, 6921, 7005, 7015],
    'LightningDealHasPrice': False,
    'PrXnID': '7798597',
    'LightningDealStartDate': None,
    'LightningDealEndDate': None,
    'LightningDealSalePrice': None,
    'ReservationGroupId': '1',
    'DeliveryGuaranteeData': [],
    'DateModified': '03/08/2023 02:07:34',
    'CountryId': 1,
    'SwatchIsOrderable': False,
    'LightningDealDateRange': None,
    'PrFixedStdShipAmount': 0,
    'CommercialGrade': False,
    'MajorPromotionVersionIds': [],
    'FreeReturnViabilityScore': None,
    'PromotionInfo': None,
    'IsComponentSoldAlone': None,
    'HasStock': True,
    'GhcId': 0,
    'HasClearanceStock': False
}